name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prek:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: prek
      - name: Run prek hooks
        uses: j178/prek-action@v2.0.4
        with:
          prek-version: "0.4.0"

  rust:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check errors
        run: cargo check --workspace --all-targets
      - name: Lint
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace --verbose
