name: napi-build

on:
  push:
    branches:
      - main
    paths:
      - "crates/whittle-napi/**"
      - "crates/whittle/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/napi-build.yml"
      - ".github/workflows/napi.yml"
  pull_request:
    paths:
      - "crates/whittle-napi/**"
      - "crates/whittle/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/napi-build.yml"
      - ".github/workflows/napi.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  napi:
    uses: ./.github/workflows/napi.yml
    with:
      crate-dir: crates/whittle-napi
      app-name: whittle
