name: release-napi

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  napi-publish:
    uses: ./.github/workflows/napi.yml
    permissions:
      contents: read
      id-token: write
    with:
      crate-dir: crates/whittle-napi
      app-name: whittle
      run-publish: true
    secrets: inherit
